USE DATABASE ECOMMERCE_DB;
USE SCHEMA RAW;

CREATE OR REPLACE PIPE RAW_PIPE
AUTO_INGEST = TRUE
AS 
COPY INTO RAW.SALES
(
    ORDER_ID, 
    ORDER_DATE,
    CUSTOMER_ID,
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    PRICE,
    CUSTOMER_CITY, 
    PAYMENT_METHOD  
)
FROM(
    SELECT 
    $1::VARCHAR,
    $2,
    $3::VARCHAR,
    $4::VARCHAR,
    $5::VARCHAR,
    $6::VARCHAR,
    $7::INTEGER,
    $8::FLOAT,
    $9::VARCHAR,
    $10::VARCHAR 
FROM @RAW.STG_CSV
)
FILE_FORMAT=(FORMAT_NAME = 'CSV_FF'
)
ON_ERROR = CONTINUE;

ALTER PIPE RAW_PIPE REFRESH;

SELECT SYSTEM$PIPE_STATUS('RAW_PIPE');

SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW.SALES',
    START_TIME => DATEADD('HOUR', -1, CURRENT_TIMESTAMP())
  )
);

SHOW PIPES;



SELECT * FROM RAW.SALES;

create table raw.rm_sales
as
(
select distinct * from raw.sales
);

select * from raw.rm_sales;

DELETE FROM RAW.SALES;