CREATE DATABASE ECOMMERCE_DB;

CREATE SCHEMA RAW;

CREATE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE RAW.SALES (
    ORDER_ID VARCHAR,
    ORDER_DATE DATE,
    CUSTOMER_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    QUANTITY INTEGER,
    PRICE FLOAT,
    CUSTOMER_CITY VARCHAR,
    PAYMENT_METHOD VARCHAR
);     

SELECT * FROM RAW.SALES;

CREATE OR REPLACE FILE FORMAT CSV_FF
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'DD-MM-YYYY';
    
CREATE OR REPLACE STAGE RAW.STG_CSV
FILE_FORMAT= CSV_FF;

DESC FILE FORMAT CSV_FF;

REMOVE @RAW.STG_CSV;

LIST @RAW.STG_CSV;

SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10 
FROM @RAW.STG_CSV;

COPY INTO RAW.SALES FROM @RAW.STG_CSV FILE_FORMAT = CSV_FF;


CREATE OR REPLACE TABLE ANALYTICS.SALES AS
SELECT
    ORDER_ID,
    ORDER_DATE,
    CUSTOMER_ID,
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    PRICE,
    QUANTITY * PRICE AS SALES_AMOUNT,
    CUSTOMER_CITY,
    PAYMENT_METHOD
FROM RAW.SALES
WHERE 1=2;

SELECT *
FROM ANALYTICS.SALES;

--Data Analyze
--Total Revenue
SELECT 
SUM(SALES_AMOUNT) AS TOTAL_REVENUE
FROM ANALYTICS.SALES;

--Revenue by Category
SELECT 
CATEGORY, SUM(SALES_AMOUNT) AS REVENUE
FROM ANALYTICS.SALES
GROUP BY CATEGORY
ORDER BY REVENUE DESC;

--Top Product
SELECT 
PRODUCT_NAME,
SUM(SALES_AMOUNT) AS REVENUE
FROM ANALYTICS.SALES
GROUP BY PRODUCT_NAME
ORDER BY REVENUE DESC;

--Revenue by City
SELECT CUSTOMER_CITY, SUM(SALES_AMOUNT) AS REVENUE
FROM ANALYTICS.SALES
GROUP BY CUSTOMER_CITY
ORDER BY REVENUE DESC;

--QUALITY CHECKS

--DUPLICATE CHECK
SELECT 
ORDER_ID, COUNT(*)
FROM ANALYTICS.SALES
GROUP BY ORDER_ID
HAVING COUNT(*) > 1;

--CHECK INVALID PRICE 
SELECT * FROM ANALYTICS.SALES
WHERE PRICE <0;

--CHECK MISSING CUSTOMER_ID
SELECT * FROM ANALYTICS.SALES
WHERE CUSTOMER_ID IS NULL;

/*SELECT ORDER_ID, SK, ISACTIVE, RANK() OVER (PARTITION BY ORDER_ID, ISACTIVE ORDER BY SK) AS RN
FROM ANALYTICS.SALES WHERE ISACTIVE = 'Y'
QUALIFY RN > 1;*/

/*INSERT INTO ANALYTICS.SALES SELECT 
    UUID_STRING() AS SK,
    ORDER_ID,
    ORDER_DATE,
    CUSTOMER_ID,
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    PRICE,
    SALES_AMOUNT,
    CUSTOMER_CITY,
    PAYMENT_METHOD,
    ISACTIVE
FROM ANALYTICS.SALES WHERE ORDER_ID = 'ORD00003';*/

/*UPDATE ANALYTICS.SALES SET ISACTIVE = 'Y';

UPDATE ANALYTICS.SALES SET ISACTIVE = 'N' WHERE SK = '7d82ee9e-e51a-4896-be8a-5ce514ddac70';

DELETE FROM ANALYTICS.SALES WHERE SK = 'f0cfeba7-d229-4c72-b848-09e8320b10b1';*/

