USE DATABASE ECOMMERCE_DB;
USE SCHEMA RAW;

CREATE OR REPLACE STREAM RAW_SALES_STREAM
ON TABLE RAW.SALES
APPEND_ONLY=TRUE;

-------------------------------------------------------------------------------------------------------

CREATE OR REPLACE TABLE RAW.SALES_PROCESSED (
    ORDER_ID VARCHAR,
    ORDER_DATE DATE,
    CUSTOMER_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    QUANTITY INTEGER,
    PRICE FLOAT,
    CUSTOMER_CITY VARCHAR,
    PAYMENT_METHOD VARCHAR
);    

------------------------------------------------------------------------------

CREATE OR REPLACE STREAM ANALYTICS.ANALYTICS_SALES_STREAM
ON TABLE RAW.SALES_PROCESSED
APPEND_ONLY=TRUE;

SHOW STREAMS;

SELECT * FROM ANALYTICS.ANALYTICS_SALES_STREAM;

SELECT * FROM RAW.SALES_PROCESSED;

DELETE FROM RAW.SALES_PROCESSED;

---------------------------------------------------------------------------------



MERGE INTO RAW.SALES_PROCESSED AS t
USING (
  SELECT DISTINCT *
  FROM RAW_SALES_STREAM
  WHERE METADATA$ACTION = 'INSERT'
) AS s
ON t.ORDER_ID = s.ORDER_ID
WHEN NOT MATCHED THEN
  INSERT (
    ORDER_ID, ORDER_DATE, CUSTOMER_ID, PRODUCT_ID, PRODUCT_NAME,
    CATEGORY, QUANTITY, PRICE, CUSTOMER_CITY, PAYMENT_METHOD
  )
  VALUES (
    s.ORDER_ID, s.ORDER_DATE, s.CUSTOMER_ID, s.PRODUCT_ID, s.PRODUCT_NAME,
    s.CATEGORY, s.QUANTITY, s.PRICE, s.CUSTOMER_CITY, s.PAYMENT_METHOD
  );

-------------------------------------------------------------------------------------------------------

MERGE INTO RAW.SALES_PROCESSED AS t
USING (
    SELECT
        ORDER_ID, ORDER_DATE, CUSTOMER_ID, PRODUCT_ID, PRODUCT_NAME,
        CATEGORY, QUANTITY, PRICE, CUSTOMER_CITY, PAYMENT_METHOD
    FROM RAW_SALES_STREAM
    WHERE METADATA$ACTION = 'INSERT'
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ORDER_ID, ORDER_DATE, CUSTOMER_ID, PRODUCT_ID, PRODUCT_NAME,
                     CATEGORY, QUANTITY, PRICE, CUSTOMER_CITY, PAYMENT_METHOD
        ORDER BY ORDER_ID
    ) = 1
) AS s
ON t.ORDER_ID = s.ORDER_ID
WHEN NOT MATCHED THEN
    INSERT (
        ORDER_ID, ORDER_DATE, CUSTOMER_ID, PRODUCT_ID, PRODUCT_NAME,
        CATEGORY, QUANTITY, PRICE, CUSTOMER_CITY, PAYMENT_METHOD
    )
    VALUES (
        s.ORDER_ID, s.ORDER_DATE, s.CUSTOMER_ID, s.PRODUCT_ID, s.PRODUCT_NAME,
        s.CATEGORY, s.QUANTITY, s.PRICE, s.CUSTOMER_CITY, s.PAYMENT_METHOD
    );
    
 