USE DATABASE ECOMMERCE_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TASK RAW.PROCESSED_SALES_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('RAW.RAW_SALES_STREAM')
AS
MERGE INTO RAW.SALES_PROCESSED AS t
USING (
    SELECT
        ORDER_ID,
        ORDER_DATE,
        CUSTOMER_ID,
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        QUANTITY,
        PRICE,
        CUSTOMER_CITY,
        PAYMENT_METHOD
    FROM RAW.RAW_SALES_STREAM
    WHERE METADATA$ACTION = 'INSERT'
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY
            ORDER_ID, ORDER_DATE, CUSTOMER_ID, PRODUCT_ID, PRODUCT_NAME,
            CATEGORY, QUANTITY, PRICE, CUSTOMER_CITY, PAYMENT_METHOD
        ORDER BY ORDER_ID
    ) = 1
) AS s
ON t.ORDER_ID = s.ORDER_ID
WHEN NOT MATCHED THEN
    INSERT (
        ORDER_ID,
        ORDER_DATE,
        CUSTOMER_ID,
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        QUANTITY,
        PRICE,
        CUSTOMER_CITY,
        PAYMENT_METHOD
    )
    VALUES (
        s.ORDER_ID,
        s.ORDER_DATE,
        s.CUSTOMER_ID,
        s.PRODUCT_ID,
        s.PRODUCT_NAME,
        s.CATEGORY,
        s.QUANTITY,
        s.PRICE,
        s.CUSTOMER_CITY,
        s.PAYMENT_METHOD
    );

    EXECUTE TASK RAW.PROCESS_SALES_TASK;

--------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE TASK ANALYTICS.ANALYTICS_SALES_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('ANALYTICS.ANALYTICS_SALES_STREAM')
AS
MERGE INTO ANALYTICS.SALES AS t
USING (
    SELECT
        ORDER_ID,
        ORDER_DATE,
        CUSTOMER_ID,
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        QUANTITY,
        PRICE,
        CUSTOMER_CITY,
        PAYMENT_METHOD
    FROM ANALYTICS.ANALYTICS_SALES_STREAM
    WHERE METADATA$ACTION = 'INSERT'
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY
            ORDER_ID, ORDER_DATE, CUSTOMER_ID, PRODUCT_ID, PRODUCT_NAME,
            CATEGORY, QUANTITY, PRICE, CUSTOMER_CITY, PAYMENT_METHOD
        ORDER BY ORDER_ID
    ) = 1
) AS s
ON t.ORDER_ID = s.ORDER_ID
WHEN NOT MATCHED THEN
    INSERT (
        ORDER_ID,
        ORDER_DATE,
        CUSTOMER_ID,
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        QUANTITY,
        PRICE,
        CUSTOMER_CITY,
        PAYMENT_METHOD
    )
    VALUES (
        s.ORDER_ID,
        s.ORDER_DATE,
        s.CUSTOMER_ID,
        s.PRODUCT_ID,
        s.PRODUCT_NAME,
        s.CATEGORY,
        s.QUANTITY,
        s.PRICE,
        s.CUSTOMER_CITY,
        s.PAYMENT_METHOD
    );

EXECUTE TASK ANALYTICS.ANALYTICS_SALES_TASK;
    SHOW TASKS;